name: Generate Snake Contribution Grid

on:
  schedule:
    # Runs at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Generate the snake contribution grid
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Golam-Rabby821
          outputs: dist/snake.svg

      # Step 3: Upload the generated SVG
      - name: Push Snake SVG to the output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          file: dist/snake.svg
